import { SECTION_IDS, TEXT_SIDE, type SectionId } from './profile'
import { anchorProgress, type Layout } from './layout'

/**
 * The serpentine, as data.
 *
 * Phase 2A parked the aircraft on the side opposite each section's text and
 * glided it to the next zone whenever the section changed. Phase 2B keeps the
 * parking but makes the *crossing* the point: across the whole scroll the
 * aircraft weaves left ↔ right in one continuous S-curve, and every crossing
 * happens in the vertical gap **between** two sections, where neither section's
 * text is near the middle of the screen.
 *
 * That constraint is the reason for the two numbers below. Section boxes are a
 * viewport tall and their text is centred, so at `u = 0.86` of a section its
 * text has climbed to the top edge of the frame, and at `u = 0.14` of the next
 * one that section's text has not yet risen off the bottom edge. Between those
 * two anchors the middle band of the screen is empty, and that is the only
 * window in which the aircraft is allowed to change sides.
 *
 * Everything here is normalized (−1 … +1 of the half-viewport, y up) and a pure
 * function of progress, which is what makes the whole flight reversible: scroll
 * up and the same curve is flown in mirror order, with no second code path.
 */

/** The crossing window, as fractions down the section on each side of the gap. */
const CROSS_FROM = 0.86
const CROSS_TO = 0.14

/** Where each section's content is considered "passed" and reveals. */
const REVEAL_U = 0.3

/** The finale window: the last ~15% of the scroll, ending inside CONTACT. */
const FINALE_FROM = { s: 3, u: 0.9 }
const FINALE_TO = { s: 4, u: 0.3 }

/**
 * Parked altitude per section, so five sections don't all hold the same height
 * and the flight reads as a route rather than a slider.
 */
const PARK_Y: Record<SectionId, number> = {
  intro: -0.1,
  work: 0.12,
  experiments: -0.18,
  about: 0.08,
  contact: -0.06,
}

/** How far the aircraft climbs through the empty gap as it crosses. */
const CROSS_ARC = 0.08

type Key = { p: number; v: number }

/** 5th-order smoothstep: zero velocity *and* zero acceleration at both ends. */
function smootherstep(t: number): number {
  return t * t * t * (t * (t * 6 - 15) + 10)
}

function sample(keys: Key[], progress: number): number {
  if (keys.length === 0) return 0
  if (progress <= keys[0].p) return keys[0].v
  const last = keys[keys.length - 1]
  if (progress >= last.p) return last.v
  for (let i = 1; i < keys.length; i++) {
    const b = keys[i]
    if (progress > b.p) continue
    const a = keys[i - 1]
    const span = b.p - a.p
    if (span <= 1e-6) return b.v
    return a.v + (b.v - a.v) * smootherstep((progress - a.p) / span)
  }
  return last.v
}

/** Anchors resolve monotonically however the layout has collapsed. */
function push(keys: Key[], p: number, v: number) {
  const prev = keys.length > 0 ? keys[keys.length - 1].p : -Infinity
  keys.push({ p: Math.max(p, prev), v })
}

export type Route = {
  /** lateral position, −1 … +1 of the half-viewport */
  x(progress: number): number
  /** altitude, −1 … +1 of the half-viewport */
  y(progress: number): number
  /** progress at which a section's content has been flown past */
  revealAt(section: number): number
  /** the finale's progress window */
  finale: { from: number; to: number }
}

export function buildRoute(layout: Layout): Route {
  const xs: Key[] = []
  const ys: Key[] = []

  SECTION_IDS.forEach((id, i) => {
    // text left → aircraft right, so the serpentine is generated by the same
    // one list that lays out the DOM (src/sections/Section.css)
    const side = TEXT_SIDE[id] === 'left' ? 1 : -1
    const parkIn = anchorProgress(layout, i, CROSS_TO)
    const parkOut = anchorProgress(layout, i, CROSS_FROM)

    push(xs, parkIn, side)
    push(xs, parkOut, side)
    push(ys, parkIn, PARK_Y[id])
    push(ys, parkOut, PARK_Y[id])

    // the crossing into the next section: one mid key so the aircraft climbs
    // through the empty band instead of sliding flat across it
    const next = SECTION_IDS[i + 1]
    if (!next) return
    const nextIn = anchorProgress(layout, i + 1, CROSS_TO)
    push(ys, (parkOut + nextIn) / 2, CROSS_ARC)
  })

  const reveal = SECTION_IDS.map((_, i) => anchorProgress(layout, i, REVEAL_U))

  return {
    x: (p) => sample(xs, p),
    y: (p) => sample(ys, p),
    revealAt: (i) => reveal[Math.max(0, Math.min(reveal.length - 1, i))] ?? 1,
    finale: {
      from: anchorProgress(layout, FINALE_FROM.s, FINALE_FROM.u),
      to: anchorProgress(layout, FINALE_TO.s, FINALE_TO.u),
    },
  }
}
